name: Test Production

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies (Bun)
        run: bun install

      - name: Run tests (Bun)
        run: bun test

      - name: Package Check
        run: bun run package:check

      - name: Test Global Install (NPM)
        run: npm install -g .
